requirements		= (OpSysAndVer == "CentOS7")
getenv			= True
executable              = CARLRunFlavours.sh
arguments               = $(argument) $(name)
output                  = CARLRun.$(ClusterId).$(ProcId).out
error                   = CARLRun.$(ClusterId).$(ProcId).err
log                     = CARLRun.$(ClusterId).log
request_memory 		= 10000 MB
should_transfer_files   = YES
request_GPUs 		= 1
request_CPUs 		= 0
+JobFlavour             = "tomorrow"
queue argument from flavours.txt